
name: Update Fork - MFI-Threshold-Breakout-Strategy

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в полночь
  workflow_dispatch:

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream
        uses: actions/checkout@v3
        with:
          repository: 'abdullah2238/MFI-Threshold-Breakout-Strategy'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: upstream

      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: 'consulfedor/MFI-Threshold-Breakout-Strategy'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: fork

      - name: Sync Fork
        run: |
          cd fork
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git pull --ff-only ../upstream/main
          git push origin main